apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-spring-boot
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: simple-spring-boot
    spec:
      containers:
      - name: simple-spring-boot
        image: registry.k8sops.mpacops.ca/example/simple-spring-boot
        ports:
        - containerPort: 8090
